export const EN = {
  home: 'home',
  Articles: 'Articles',
  TECH: 'TECH',
  Life: 'Life',
  Our: 'Our',
  Photos: 'Photos',
  Videos: 'Videos',
  About: 'About',
  Lucaus: 'Lucaus',
  Betty: 'Betty',
  Website: 'Website',
  Search: 'Search',
  Settings: 'Settings',
  Theme: 'Theme',
  Language: 'Language',
  Navigation: 'Navigation',
  Recent: 'Recent',
  ['Enter to search']: 'Enter to search',
  ["Lucaus's project"]: "Lucaus's project",
  ["Betty's project"]: "Betty's project",
  ['Our project']: 'Our project',
  ['404 Page Not Found']: '404 Page Not Found'
};

export const CN = {
  home: '首页',
  Articles: '文章',
  TECH: '技术',
  Life: '生活',
  Our: '我们',
  Photos: '照片',
  Videos: '视频',
  About: '关于',
  Lucaus: 'Lucaus',
  Betty: 'Betty',
  Website: '网站',
  Search: '搜索',
  Settings: '设置',
  Theme: '主题',
  Language: '语言',
  Navigation: '导航',
  Recent: '最近',
  ['Enter to search']: '回车进行搜索',
  ["Lucaus's project"]: 'Lucaus 的项目',
  ["Betty's project"]: 'Betty 的项目',
  ['Our project']: '我们的项目',
  ['404 Page Not Found']: '404 页面未找到'
};
