export const EN = {
  home: 'home',
  Novel: 'Novel',
  Stark: 'Stark',
  Life: 'Life',
  Our: 'Our',
  Photos: 'Photos',
  Videos: 'Videos',
  About: 'About',
  Lucaus: 'Lucaus',
  Betty: 'Betty',
  Website: 'Website',
  Search: 'Search',
  Settings: 'Settings',
  Theme: 'Theme',
  Language: 'Language',
  Navigation: 'Navigation',
  Recent: 'Recent',
  info: 'info',
  success: 'success',
  warning: 'warning',
  error: 'error',
  Diary: 'Diary',
  Love: 'Love',
  ["Stark's novels"]: "Stark's novels",
  ['Article cover']: 'Article cover',
  ['Enter to search']: 'Enter to search',
  ["Lucaus's project"]: "Lucaus's project",
  ["Betty's project"]: "Betty's project",
  ['Our project']: 'Our project',
  ['404 Page Not Found']: '404 Page Not Found',
  ['News :']: 'News :',
  // 错误处理适配
  ['获取文章内容失败']: 'Get article content failed'
};

export const CN = {
  home: '首页',
  Novel: '小说',
  Stark: 'Stark',
  Life: '生活',
  Our: '我们',
  Photos: '照片',
  Videos: '视频',
  About: '关于',
  Lucaus: 'Lucaus',
  Betty: 'Betty',
  Website: '网站',
  Search: '搜索',
  Settings: '设置',
  Theme: '主题',
  Language: '语言',
  Navigation: '导航',
  Recent: '最近',
  info: '通知',
  success: '成功',
  warning: '警告',
  error: '错误',
  Diary: '日记',
  Love: '珍惜',
  ["Stark's novels"]: 'Stark 的小说',
  ['Article cover']: '文章封面',
  ['Enter to search']: '回车进行搜索',
  ["Lucaus's project"]: 'Lucaus 的项目',
  ["Betty's project"]: 'Betty 的项目',
  ['Our project']: '我们的项目',
  ['404 Page Not Found']: '404 页面未找到',
  ['News :']: '新闻 :',
  // 错误处理适配
  ['获取文章内容失败']: '获取文章内容失败'
};
