export const EN = {
  home: 'home',
  Novel: 'Novel',
  Stark: 'Stark',
  Life: 'Life',
  Our: 'Our',
  Photos: 'Photos',
  Videos: 'Videos',
  About: 'About',
  Lucaus: 'Lucaus',
  Betty: 'Betty',
  Website: 'Website',
  Search: 'Search',
  Settings: 'Settings',
  Theme: 'Theme',
  Language: 'Language',
  Navigation: 'Navigation',
  Recent: 'Recent',
  info: 'info',
  success: 'success',
  warning: 'warning',
  error: 'error',
  Diary: 'Diary',
  Love: 'Love',
  ["Stark's novels"]: "Stark's novels",
  ['Article cover']: 'Article cover',
  ['Enter to search']: 'Enter to search',
  ["Lucaus's project"]: "Lucaus's project",
  ["Betty's project"]: "Betty's project",
  ['Our project']: 'Our project',
  ['404 Page Not Found']: '404 Page Not Found',
  ['News :']: 'News :',
  // 错误处理适配
  ['获取文章内容失败']: 'Get article content failed',
  ['lucausBio']: `Hello, I’m Lucaus, a tech enthusiast passionate about front-end development. I graduated from SSU (Shanghai Second Polytechnic University), and since then, I’ve been working in front-end development, accumulating extensive project experience and technical expertise. In the field of front-end development, I am proficient in a variety of popular technologies and frameworks, including but not limited to React, Vue, and others. I’m also familiar with front-end build tools and modular development, enabling me to flexibly adapt to different project requirements. I’m passionate about seamlessly integrating design with code to create user interfaces that are both beautiful and efficient. In addition to technical implementation, I focus on performance optimization and user experience in front-end development, striving to ensure that every project is highly maintainable and scalable. By continuously learning and exploring new front-end technologies, I maintain my enthusiasm and pursuit of technology, aiming to improve myself and create innovative solutions in this fast-evolving industry. If you're interested in front-end development or have potential collaboration opportunities, feel free to reach out! Let’s exchange ideas and grow together.`,
  ['Blogger']: 'Blogger',
  ['web developer']: 'web developer',
  [`I'm a`]: `I'm a`,
  ['copySuccess']: 'Copy success'
};

export const CN = {
  home: '首页',
  Novel: '小说',
  Stark: 'Stark',
  Life: '生活',
  Our: '我们',
  Photos: '照片',
  Videos: '视频',
  About: '关于',
  Lucaus: 'Lucaus',
  Betty: 'Betty',
  Website: '网站',
  Search: '搜索',
  Settings: '设置',
  Theme: '主题',
  Language: '语言',
  Navigation: '导航',
  Recent: '最近',
  info: '通知',
  success: '成功',
  warning: '警告',
  error: '错误',
  Diary: '日记',
  Love: '珍惜',
  ["Stark's novels"]: 'Stark 的小说',
  ['Article cover']: '文章封面',
  ['Enter to search']: '回车进行搜索',
  ["Lucaus's project"]: 'Lucaus 的项目',
  ["Betty's project"]: 'Betty 的项目',
  ['Our project']: '我们的项目',
  ['404 Page Not Found']: '404 页面未找到',
  ['News :']: '新闻 :',
  // 错误处理适配
  ['获取文章内容失败']: '获取文章内容失败',
  ['lucausBio']: `你好，我是 Lucaus，一名热爱前端开发的技术爱好者。我毕业于SSU（上海第二工业大学），自毕业以来，一直从事前端开发工作，积累了丰富的项目经验和技术沉淀。在前端开发领域，我擅长使用各种主流技术和框架，包括但不限于React、Vue等，熟悉前端构建工具和模块化开发，能够灵活应对不同项目需求。我热衷于将设计与代码完美结合，创造出既美观又高效的用户界面。除了技术实现，我也注重前端开发的性能优化与用户体验，力求每一个项目都能达到高可维护性与高可扩展性。通过不断学习和探索新的前端技术，我始终保持对技术的热情与追求，希望在这个快速发展的行业中不断提升自己，创造更多创新的解决方案。如果你对前端开发感兴趣，或者有合作的机会，欢迎随时联系我！我们一起交流技术，共同成长。`,
  ['Blogger']: '博主',
  ['web developer']: '网站开发者',
  [`I'm a`]: `我是一名`,
  ['copySuccess']: '复制成功'
};
